source 'https://github.com/CocoaPods/Specs.git'

pod 'MFSideMenu'
pod 'ChameleonFramework'
pod 'HexColors'
pod 'RMPickerViewController'
pod 'AKLocationManager'
pod 'AFPopupView'
pod 'TPKeyboardAvoiding'
pod 'FXForms'